In [1]:
import torch
from torchinfo import summary
import torchvision

In [2]:
from model import MLP_ELU_convex
model = MLP_ELU_convex()

In [6]:
summary(model, input_size=(1, 64))

Layer (type:depth-idx)                   Output Shape              Param #
MLP_ELU_convex                           [1, 40]                   --
├─Sequential: 1-1                        [1, 40]                   --
│    └─Linear: 2-1                       [1, 64]                   4,160
│    └─SiLU: 2-2                         [1, 64]                   --
│    └─Linear: 2-3                       [1, 48]                   3,120
│    └─SiLU: 2-4                         [1, 48]                   --
│    └─Linear: 2-5                       [1, 48]                   2,352
│    └─SiLU: 2-6                         [1, 48]                   --
│    └─Linear: 2-7                       [1, 40]                   1,960
│    └─SiLU: 2-8                         [1, 40]                   --
│    └─Linear: 2-9                       [1, 40]                   1,640
│    └─SiLU: 2-10                        [1, 40]                   --
├─Linear: 1-2                            [1, 40]                   1,6

In [11]:
celeba_train = torchvision.datasets.CelebA(root='../datasets', split='train')
celeba_val = torchvision.datasets.CelebA(root='../datasets', split='valid')

In [12]:
len(celeba_train)

162770

In [13]:
len(celeba_val)

19867

In [14]:
len(celeba_val) / (len(celeba_val) + len(celeba_train))

0.10877861550507291

In [3]:
X, y = torch.load('../datasets/celeba_deep_embeddings_w_y.pt')

/tmp/user/5678/ipykernel_3681651/149163974.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  X, y = torch.load('../datasets/celeba_deep_embeddings_w_y.pt')


In [4]:
model.load_state_dict(torch.load('/usr/people/robertwiebe/ml_geometry_project/latent_attribute_prediction/checkpoints/last_checkpoint.pt')['model_state_dict'])

/tmp/user/5678/ipykernel_3681651/2329267043.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load('/usr/people/robertwiebe/ml_geometry_project

<All keys matched successfully>

In [8]:
y[0]

tensor([0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 0.,
        1., 0., 0., 1.])

In [7]:
model(X[0]) >= .5

tensor([False, False,  True, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False,  True, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,  True])

In [9]:
y.sum() / y.numel()

tensor(0.2258)

In [13]:
torch.where(y[0].bool(), 5, 2)

tensor([2, 5, 5, 2, 2, 2, 2, 2, 2, 2, 2, 5, 2, 2, 2, 2, 2, 2, 5, 5, 2, 5, 2, 2,
        5, 2, 2, 5, 2, 2, 2, 5, 5, 2, 5, 2, 5, 2, 2, 5])

In [ ]:
torch.nn.functional.binary_cross_entropy(model(X[0]), y[0], weight=torch.where())

tensor(0.4067, grad_fn=<BinaryCrossEntropyBackward0>)

In [16]:
dataset = torch.utils.data.TensorDataset(X, y)

In [17]:
train_set, val_set = torch.utils.data.random_split(dataset, [0.9, 0.1])

In [19]:
len(train_set)

182340

In [21]:
len(val_set)

20259